# Generated by Django 5.1.1 on 2024-10-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
