# Generated by Django 5.1.1 on 2024-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_alter_cartitem_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
