# Generated by Django 5.1.1 on 2024-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
