# Generated by Django 5.1.1 on 2024-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0004_remove_menuitem_menu_image_menuitem_menu_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
