# Generated by Django 5.1.1 on 2024-10-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
